name: Say hello # Nombre del WOrkflows

on: # Activar un workflow
  push: # Evento push
    branches: # Ramas en este caso main
      - main

jobs: # Trabajos que va a realizar
  hello_world: # Nombre del trabajo que va a realizar
    runs-on: ubuntu-18.04 # En que S.O va a funcionar
    steps: # Pasos que va a seguir
      - name: Echo the message # Nombre a los pasos que va a seguir
        run: |
          echo "Hola midu!"
      - name: Dime la fecha
        run: date
      - run: ls -l